apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zonetax.fullname" . }}-collector
  labels:
    {{- include "zonetax.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .Values.collector.replicas }}
  selector:
    matchLabels:
      {{- include "zonetax.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        {{- include "zonetax.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ include "zonetax.serviceAccountName" . }}
      containers:
        - name: collector
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zonetax.fullname" . }}-collector
  labels:
    {{- include "zonetax.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "zonetax.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
