agent:
  image:
    repository: ghcr.io/gargkrishna730/zonetax-agent
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  sampleIntervalSeconds: 15
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

collector:
  image:
    repository: ghcr.io/gargkrishna730/zonetax-collector
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

serviceAccount:
  create: true
  name: ""

alerting:
  slackWebhookUrl: ""
  thresholdUsdPerHour: 5
