#!/usr/bin/env bash
# Regenerates deploy/manifests/install.yaml from the Helm chart (the single source of truth).
# Run after changing anything under deploy/helm/. CI fails if the committed file is stale.
set -euo pipefail
cd "$(dirname "$0")/.."
out=deploy/manifests/install.yaml
{
  echo "# ZoneTax raw Kubernetes manifests. GENERATED by hack/gen-manifests.sh from deploy/helm/zonetax."
  echo "# Do not edit by hand. Install: kubectl apply -f install.yaml"
  echo "---"
  echo "apiVersion: v1"
  echo "kind: Namespace"
  echo "metadata:"
  echo "  name: zonetax"
  helm template zonetax deploy/helm/zonetax --namespace zonetax
} > "$out"
echo "wrote $out"
